// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfofwwswropqkewapnze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmb2Z3d3N3cm9wcWtld2FwbnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NTQwMjcsImV4cCI6MjA1NDQzMDAyN30.B5pAKPcrbT6L4VUQqq2-0VlmRynhTxNhQzQ-sXQA9E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);